version: '3.5'

services:
  reverse-proxy:
    image: traefik:v2.2
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
      - ./devcerts:/etc/certs
      - ./log:/etc/log
    networks:
      - webgateway

networks:
  webgateway:
    driver: bridge
    name: local_traefik_webgateway
